### ISSUE TITLE
Multiple terminals for load/run

### ISSUE THREAD

**Issue by massung** [Eugleo/magic-racket#11]
When using the `load` and `run` command (back and forth), I can end up with multiple "Racket" and "Racket REPL" terminal instances. My guess - from the code - is that there should only be one of each ever.

For the `run` terminal, I imagine it'd be desirable to `.dispose()` of it and create a new one before launching a new run command?

**Comment by Eugleo** [comment]
That's semi-expected. `Load` and `run` commands both have two versions, one opening a new terminal, and one executing _in the current (-ly focused) terminal_ (or REPL). By focusing a particular terminal, the user explicitly decides which terminal will the commands use.

I couldn't settle on a better UX, so I made one that's simple to understand so that it would fit into everyone's workflow: open here, or open elsewhere. I agree that at least the naming could be improved, and generally that this probably isn't ideal.

I'm open to suggestions, but I'd be wary of any "magical" behaviours if they aren't 100% intuitive.

**Comment by massung** [comment]
I completely understand. My comment is just that I feel it's unintuitive (to me) currently. 

Consider this workflow:

#### I load my source file. Play in the REPL a bit, and then edit code and click load again.

My expectation (and is what happens) is that it sends the file to the same REPL, and I can keep working in it with updated code.

#### Now I think I'm at a good place and click run.

My expectation (and is what happens) is that a new, fresh terminal is opened and the program runs to completion. In the terminal I see whatever output is left. 

It's unclear to me (a new user) whether the existing terminal was disposed of (since I'm running) or still hanging around for me to keep working in. Either is fine, but I didn't know which was the case.

#### I make a few new code changes and click load again.

My expectation (not necessarily yours) here is NOT what actually happens. I would think that one of the following would happen:

1. It would either continue using the existing "load" terminal where I was working previously; or
2. It would dispose of the old "load" terminal (likely when I clicked "run"?) and now makes a new "load" terminal for me to work in.

However, neither of these is what happens. Instead, it makes a new "load" terminal, but the old one is still lingering: using CPU/RAM with another Racket process. 

Worse yet, I can't use the Terminal dropdown list of open terminals to identify which ones to keep/dispose because they are all named "Racket REPL". So, if I end accidentally switching the terminal I was working in, I won't really know which one I _should_ be in to get back to.

Anyway, my 2 cents. :smile:

**Comment by Eugleo** [comment]
Thanks for the detailed run through of the workflow — I think what you wrote makes perfect sense. I’ll make it so that the file will always be loaded in the same repl. Then I can name the terminals a little more clearly as well (now, as I didn’t really know what’s in them, “Racket REPL” is the best I can make).

**Comment by massung** [comment]
Perhaps run could do "Racket Output" (or "<filename> Output") and load could be "Racket REPL"? Just tossing out ideas.

**Comment by Eugleo** [comment]
I was thinking of doing "REPL (filename.rkt)” and something similar for the restults of run as well — Output sounds good.
