### ISSUE TITLE
Feature Request: Paredit

### ISSUE THREAD

**Issue by Immortalin** [Eugleo/magic-racket#28]
https://github.com/BetterThanTomorrow/calva/tree/master/src/paredit

**Comment by Eugleo** [comment]
Wasn't there a Paredit VSCode extesion? I would prefer not to increase the maintain burden unecessarilly.

**Comment by geekarist** [comment]
@Eugleo If not including the feature in Magic Racket, perhaps add a few lines in the README or the wiki, to point to an extension that plays well with Magic Racket? What would you recommend? I've tried  [Strict Paredit](https://github.com/ailisp/strict-paredit-vscode) but I had to set it up to make it work well.

**Comment by Eugleo** [comment]
I don't mind adding whatever some links to other extensions into the readme, but I don't use any besides Magic Racket, so I'd outside help on this. Does strict paredit work for you? What did you have to set up?

**Comment by geekarist** [comment]
In fact I think I made it work but partially. The problem is that Strict Paredit activates only on Scheme or Lisp files, not Racket. 
By associating `.rkt` files to the Scheme file type I can activate Strict Paredit but it disables most of Magic Racket, in particular the LSP and some keyboard shortcuts.
The best fix for me would be to change Strict Paredit to make it work with Racket files. I'll try that when I have the time.

**Comment by geekarist** [comment]
In fact there is a PR already since 2020 on Strict Paredit to add Racket support, but it hasn't been merged.

For now my solution was to generate a `.vsix` from that fork and install it locally. I also pinged the maintainer to merge the PR but we'll see about that. Thanks anyway.
