### ISSUE TITLE
Add command to open REPL without loading file or selection

### ISSUE THREAD

**Issue by tautologico** [Eugleo/magic-racket#5]
Sometimes it's useful to open a REPL to experiment without having to load a file, so I think this could be added as a command. Currently it's also not possible to open a REPL and load an unsaved file (maybe this should be another issue?), so it makes even more sense to have a command to start up a REPL without a file.

**Comment by Eugleo** [comment]
You're right, the REPL "UX" is pretty much in beta. I'd like the commands to be as modular as possible, so that every thinkable REPL workflow will be doable just by chaining some of them. And providing sane defaults is another thing.

Once we leave the "one file one repl" territory, we have to answer some new design-related questions. Let's say the user opens repl without a file → creates a file → runs the file in repl. Should a new repl be opened? Or should it be run in the current repl? Or should we provide both commands (run file in current repl, run file in new repl) and let the user decide? And in that case, what will be the default?

**Comment by Eugleo** [comment]
This should be fixed by c5335e73f88c9d1454181af122f74fd159067c1a. It is now possible to open a REPL without needing to open a file first. There have been some other changes to how REPLs are being handled (most of the magic was removed) — please see the README for a complete description of the current state of things.

The update has been pushed to the marketplace.
